import Head from "next/head";
import Link from "next/link";
import Input from "postcss/lib/input";

import {TodoList} from "../components/todoList"

import { api } from "src/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        <title>To-do List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">To-Do List</span>
          </h1>
            <TodoList/>
          
          {/* <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p> */}
        </div>
      </main>
    </>
  );
}
